### ISSUE TITLE
ubuntu and r-ver keeps failing

### ISSUE THREAD

**Issue by rynge** [opensciencegrid/cvmfs-singularity-sync#423]
We have two images which keeps failing:

```
registry.hub.docker.com/library/ubuntu:latest
registry.hub.docker.com/rocker/r-ver:latest
```

But they can be pulled by hand, which makes me think there is something in our code causing the problem.

```
Traceback (most recent call last):
  File "/github/workspace/./cvmfs-singularity-sync", line 480, in verify_image
    hub.manifest(namespace, repo_name, repo_tag, head=True)
  File "/github/workspace/dockerhub.py", line 532, in manifest
    return self._do_requests_head(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 340, in _do_requests_head
    return self._do_request('HEAD', address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 318, in _do_request
    return self._do_request(method, address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 320, in _do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://registry.hub.docker.com/v2/library/ubuntu/manifests/latest
Traceback (most recent call last):
  File "/github/workspace/./cvmfs-singularity-sync", line 204, in main
    retval = verify_image(image, registry, doauth, manifest_cache)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/./cvmfs-singularity-sync", line 480, in verify_image
    hub.manifest(namespace, repo_name, repo_tag, head=True)
  File "/github/workspace/dockerhub.py", line 532, in manifest
    return self._do_requests_head(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 340, in _do_requests_head
    return self._do_request('HEAD', address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 318, in _do_request
    return self._do_request(method, address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 320, in _do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://registry.hub.docker.com/v2/library/ubuntu/manifests/latest
Traceback (most recent call last):
  File "/github/workspace/./cvmfs-singularity-sync", line 480, in verify_image
    hub.manifest(namespace, repo_name, repo_tag, head=True)
  File "/github/workspace/dockerhub.py", line 532, in manifest
    return self._do_requests_head(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 340, in _do_requests_head
    return self._do_request('HEAD', address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 318, in _do_request
    return self._do_request(method, address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 320, in _do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://registry.hub.docker.com/v2/library/ubuntu/manifests/latest
Traceback (most recent call last):
  File "/github/workspace/./cvmfs-singularity-sync", line 204, in main
    retval = verify_image(image, registry, doauth, manifest_cache)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/./cvmfs-singularity-sync", line 480, in verify_image
    hub.manifest(namespace, repo_name, repo_tag, head=True)
  File "/github/workspace/dockerhub.py", line 532, in manifest
    return self._do_requests_head(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 340, in _do_requests_head
    return self._do_request('HEAD', address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 318, in _do_request
    return self._do_request(method, address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 320, in _do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://registry.hub.docker.com/v2/library/ubuntu/manifests/latest
Traceback (most recent call last):
  File "/github/workspace/./cvmfs-singularity-sync", line 480, in verify_image
    hub.manifest(namespace, repo_name, repo_tag, head=True)
  File "/github/workspace/dockerhub.py", line 532, in manifest
    return self._do_requests_head(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 340, in _do_requests_head
    return self._do_request('HEAD', address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 318, in _do_request
    return self._do_request(method, address, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/github/workspace/dockerhub.py", line 320, in _do_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://registry.hub.docker.com/v2/library/ubuntu/manifests/latest
```

**Comment by djw8605** [comment]
The patch https://github.com/opensciencegrid/cvmfs-singularity-sync/commit/7ee658946633d3cbefa6b707d08c913a78a04735 should have fixed this issue.  If you continue to see issues, let us know.
